# Generated by Django 5.0.6 on 2024-06-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, null=True)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'publication_journal',
            },
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField()),
            ],
            options={
                'db_table': 'web_link',
            },
        ),
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'web_resource',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('authors', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('reference', models.TextField(null=True)),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.publicationjournal')),
                ('web_link', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink')),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.AddField(
            model_name='weblink',
            name='web_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.webresource'),
        ),
    ]
