# Generated by Django 5.1.2 on 2025-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationjournal',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
