# Generated by Django 5.1.2 on 2025-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_publicationjournal_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResiduePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('ccn_number', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
