# Generated by Django 5.1.2 on 2025-06-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_residueposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residueposition',
            old_name='number',
            new_name='position',
        ),
    ]
