# Generated by Django 4.2.7 on 2024-01-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'journal',
            },
        ),
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'web_resource',
            },
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField()),
                ('web_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.webresource')),
            ],
            options={
                'db_table': 'web_link',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('authors', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.journal')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink')),
            ],
            options={
                'db_table': 'publication',
            },
        ),
    ]
