# Generated by Django 5.0.1 on 2024-04-17 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='web_link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.TextField(null=True),
        ),
    ]
