# Generated by Django 5.0.1 on 2024-04-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_publication_web_link_alter_publication_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, null=True)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'publication_journal',
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.publicationjournal'),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
