# Generated by Django 4.2.5 on 2023-10-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemokineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemokinetype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
            ],
            options={
                'db_table': 'sequence',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uniprot', models.CharField(db_index=True, max_length=100, null=True)),
                ('family', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('chemokinetype', models.CharField(max_length=200)),
                ('sequence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.sequence')),
            ],
            options={
                'db_table': 'protein',
            },
        ),
    ]
