# Generated by Django 4.2.5 on 2023-10-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0005_alter_species_common_name_alter_species_latin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniprot',
            old_name='uniprot',
            new_name='uniprot_id',
        ),
    ]
