# Generated by Django 4.2.5 on 2023-10-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0008_alter_protein_sequence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
