# Generated by Django 5.0.1 on 2024-04-15 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0012_remove_proteinsegment_fully_aligned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinSequenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'protein_sequence_type',
            },
        ),
        migrations.CreateModel(
            name='ProteinState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'protein_state',
            },
        ),
        migrations.AddField(
            model_name='protein',
            name='sequence_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinsequencetype'),
        ),
        migrations.CreateModel(
            name='ProteinConformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.proteinstate')),
            ],
            options={
                'db_table': 'protein_conformation',
                'ordering': ('id',),
            },
        ),
    ]
