# Generated by Django 5.0.1 on 2024-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('protein', '0014_proteinsource_protein_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='web_links',
            field=models.ManyToManyField(to='common.weblink'),
        ),
    ]
