# Generated by Django 5.0.1 on 2024-04-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0016_proteinalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.SmallIntegerField()),
                ('proteins', models.ManyToManyField(related_name='genes', to='protein.protein')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.species')),
            ],
            options={
                'db_table': 'gene',
                'ordering': ('position',),
                'unique_together': {('name', 'species', 'position')},
            },
        ),
    ]
