# Generated by Django 5.0.1 on 2024-04-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0017_gene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='pdb_list',
        ),
        migrations.AddField(
            model_name='protein',
            name='accession',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
