# Generated by Django 5.0.6 on 2024-06-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidueFragmentInteractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50, null=True)),
                ('direction', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'interaction_type_residue_fragment',
            },
        ),
        migrations.CreateModel(
            name='ChemokinePartnerPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemokine_chain', models.CharField(max_length=3, null=True)),
                ('partner_chain', models.CharField(max_length=3, null=True)),
                ('chemokine_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemokine_entities', to='structure.entity')),
                ('partner_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_entities', to='structure.entity')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'interaction_chemokine_partner_pair',
            },
        ),
        migrations.CreateModel(
            name='ChemokinePartnerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_residue', models.CharField(max_length=10, null=True)),
                ('partner_chain', models.CharField(max_length=3, null=True)),
                ('interaction_type', models.CharField(max_length=100, null=True)),
                ('chemokine_residue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.rotamer')),
                ('chemokine_partner_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_details', to='interaction.chemokinepartnerpair')),
            ],
            options={
                'db_table': 'interaction_chemokine_partner_interaction',
            },
        ),
        migrations.CreateModel(
            name='ChemokinePartnerIFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifp_string', models.CharField(max_length=2000, null=True)),
                ('chemokine_partner_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ifp_entries', to='interaction.chemokinepartnerpair')),
            ],
            options={
                'db_table': 'interaction_chemokine_partner_IFP',
            },
        ),
        migrations.CreateModel(
            name='StructurePartnerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_reference', models.CharField(max_length=3, null=True)),
                ('annotated', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
                ('pdb_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'interaction_structure_partner',
            },
        ),
        migrations.CreateModel(
            name='ResidueFragmentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.fragment')),
                ('rotamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.rotamer')),
                ('interaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.residuefragmentinteractiontype')),
                ('structure_partner_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.structurepartnerinteraction')),
            ],
            options={
                'db_table': 'interaction_residue_fragment',
            },
        ),
    ]
