# Generated by Django 5.0.6 on 2024-06-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigandNetworkHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligand_name', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligand_network_htmls', to='structure.structure')),
            ],
            options={
                'db_table': 'ligand_network_html',
            },
        ),
    ]
