# Generated by Django 5.1.2 on 2025-01-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_ligandnetworkhtml'),
        ('structure', '0004_structure_chain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinepartnerinteraction',
            name='structure',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
            preserve_default=False,
        ),
    ]
