# Generated by Django 5.0.1 on 2024-04-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_residuefragmentinteraction_fragment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemokinepartnerinteraction',
            name='chemokine_partner_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction.chemokinepartnerpair'),
        ),
    ]
