# Generated by Django 5.1.2 on 2025-01-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_chemokinepartnerinteraction_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemokinepartnerinteraction',
            name='structure',
        ),
    ]
