# Generated by Django 5.0.1 on 2024-04-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_alter_chemokinepartnerinteraction_chemokine_partner_pair'),
        ('residue', '0002_alter_residue_options_remove_residue_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemokinepartnerinteraction',
            name='chemokine_residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.residue'),
        ),
    ]
