# Generated by Django 5.1.2 on 2025-01-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_chemokinepartnerinteraction_structure'),
        ('structure', '0005_alter_structure_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemokinepartnerifp',
            name='chemokine_partner_pair',
        ),
        migrations.AddField(
            model_name='chemokinepartnerifp',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
    ]
