# Generated by Django 5.0.1 on 2024-05-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_remove_chemokinepartnerinteraction_chemokine_partner_pair_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chemokinepartnerinteraction',
            table='interaction_chemokine_partner_interaction',
        ),
        migrations.AlterModelTable(
            name='chemokinepartnerpair',
            table='interaction_chemokine_partner_pair',
        ),
    ]
