# Generated by Django 5.1.2 on 2025-02-14 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_remove_chemokinepartnerifp_chemokine_partner_pair_and_more'),
        ('structure', '0006_chemokinebindingpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinepartnerifp',
            name='binding_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.chemokinebindingpartner'),
        ),
    ]
