# Generated by Django 5.1.2 on 2025-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_chemokinepartnerifp_binding_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinepartnerinteraction',
            name='partner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
