# Generated by Django 5.1.2 on 2025-04-02 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_chemokinepartnerinteraction_partner_name'),
        ('structure', '0009_chemokinebindingpartner_partner_residues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemokinepartnerinteraction',
            name='chemokine_partner_pair',
        ),
        migrations.AddField(
            model_name='chemokinepartnerinteraction',
            name='chemokine_binding_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.chemokinebindingpartner'),
        ),
    ]
