# Generated by Django 5.1.2 on 2025-04-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0009_remove_chemokinepartnerinteraction_chemokine_partner_pair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residuefragmentinteraction',
            name='interaction_type',
        ),
        migrations.DeleteModel(
            name='ChemokinePartnerPair',
        ),
        migrations.DeleteModel(
            name='ResidueFragmentInteractionType',
        ),
    ]
