# Generated by Django 5.1.2 on 2025-09-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0012_gtp_binding_affinity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinegpcrgtpbinding',
            name='type',
            field=models.CharField(blank=True, help_text='e.g., agonist/antagonist/modulator', max_length=64, null=True),
        ),
    ]
