# Generated by Django 5.1.2 on 2025-09-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0013_chemokinegpcrgtpbinding_type'),
        ('structure', '0019_predictedcomplex_gpcr_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedChemokinePartnerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemokine_chain', models.CharField(blank=True, max_length=10, null=True)),
                ('chemokine_residue_number', models.IntegerField(blank=True, null=True)),
                ('chemokine_residue_name', models.CharField(blank=True, max_length=5, null=True)),
                ('partner_chain', models.CharField(blank=True, max_length=10, null=True)),
                ('partner_residue_number', models.IntegerField(blank=True, null=True)),
                ('partner_residue_name', models.CharField(blank=True, max_length=5, null=True)),
                ('interaction_type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('predicted_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_interactions', to='structure.predictedcomplex')),
            ],
            options={
                'db_table': 'interaction_predicted_chemokine_partner',
                'indexes': [models.Index(fields=['predicted_complex', 'interaction_type'], name='interaction_predict_bed8d3_idx')],
                'unique_together': {('predicted_complex', 'chemokine_chain', 'chemokine_residue_number', 'partner_chain', 'partner_residue_number', 'interaction_type')},
            },
        ),
    ]
