# Generated by Django 5.1.2 on 2025-09-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0015_predictedchemokinepartnerinteraction_generic'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='predictedchemokinepartnerinteraction',
            new_name='interaction_predict_ed3238_idx',
            old_name='interaction_predicted_generic_idx',
        ),
    ]
