# Generated by Django 5.1.2 on 2025-09-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0016_predictedchemokinepartnerinteraction_chemresidue'),
        ('interaction', '0016_rename_interaction_predicted_generic_idx_interaction_predict_ed3238_idx'),
    ]

    operations = [
    ]
