# Generated by Django 4.2.7 on 2023-12-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0007_rename_pdbs_partner_structures'),
        ('structure', '0015_alter_structure_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemokinePartnerPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'chemokine_partner_pair',
            },
        ),
        migrations.CreateModel(
            name='ChemokinePartnerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemokine_residue', models.CharField(max_length=10, null=True)),
                ('partner_residue', models.CharField(max_length=10, null=True)),
                ('interaction_type', models.CharField(max_length=50, null=True)),
                ('chemokine_partner_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.chemokinepartnerpair')),
            ],
            options={
                'db_table': 'chemokine_partner_interaction',
            },
        ),
    ]
