# Generated by Django 5.0.1 on 2024-04-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_residuefragmentinteraction_and_more'),
        ('partner', '0008_partnertype_rename_type_partner_partner_type_and_more'),
        ('structure', '0040_fragment_rotamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='residuefragmentinteraction',
            name='fragment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.fragment'),
        ),
        migrations.AddField(
            model_name='residuefragmentinteraction',
            name='rotamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.rotamer'),
        ),
        migrations.AddField(
            model_name='residuefragmentinteraction',
            name='interaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.residuefragmentinteractiontype'),
        ),
        migrations.AddField(
            model_name='structurepartnerinteraction',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
        migrations.AddField(
            model_name='structurepartnerinteraction',
            name='pdb_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata'),
        ),
        migrations.AddField(
            model_name='structurepartnerinteraction',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
        migrations.AddField(
            model_name='residuefragmentinteraction',
            name='structure_partner_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.structurepartnerinteraction'),
        ),
    ]
