# Generated by Django 5.0.1 on 2024-04-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_alter_chemokinepartnerinteraction_chemokine_residue'),
        ('structure', '0042_rotamer_pdbseq_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemokinepartnerinteraction',
            name='chemokine_partner_pair',
        ),
        migrations.AlterField(
            model_name='chemokinepartnerinteraction',
            name='chemokine_residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.rotamer'),
        ),
    ]
