# Generated by Django 5.0.1 on 2024-05-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_alter_chemokinepartnerinteraction_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinepartnerinteraction',
            name='partner_chain',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
