# Generated by Django 5.0.1 on 2024-05-27 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_chemokinepartnerinteraction_partner_chain'),
        ('structure', '0050_rotamer_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemokinepartnerpair',
            name='partner',
        ),
        migrations.AddField(
            model_name='chemokinepartnerinteraction',
            name='chemokine_partner_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='interaction.chemokinepartnerpair'),
        ),
        migrations.AddField(
            model_name='chemokinepartnerpair',
            name='chemokine_chain',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='chemokinepartnerpair',
            name='partner_chain',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='ChemokinePartnerIFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemokine_chain', models.CharField(max_length=10, null=True)),
                ('partner_chain', models.CharField(max_length=10, null=True)),
                ('ifp_string', models.CharField(max_length=2000, null=True)),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'interaction_chemokine_partner_IFP',
            },
        ),
    ]
