# Generated by Django 5.0.1 on 2024-05-27 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0009_remove_chemokinepartnerpair_partner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemokinepartnerifp',
            name='chemokine_chain',
        ),
        migrations.RemoveField(
            model_name='chemokinepartnerifp',
            name='partner_chain',
        ),
        migrations.RemoveField(
            model_name='chemokinepartnerifp',
            name='structure',
        ),
        migrations.AddField(
            model_name='chemokinepartnerifp',
            name='chemokine_partner_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ifp_entries', to='interaction.chemokinepartnerpair'),
        ),
        migrations.AlterField(
            model_name='chemokinepartnerinteraction',
            name='chemokine_partner_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_details', to='interaction.chemokinepartnerpair'),
        ),
        migrations.AlterField(
            model_name='chemokinepartnerinteraction',
            name='interaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chemokinepartnerinteraction',
            name='partner_chain',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
