# Generated by Django 4.2.5 on 2023-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_delete_pdbinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='model',
            name='chemokinetype',
        ),
        migrations.RemoveField(
            model_name='model',
            name='family',
        ),
        migrations.RemoveField(
            model_name='model',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='model',
            name='species',
        ),
        migrations.RemoveField(
            model_name='model',
            name='uniprot_id',
        ),
        migrations.AddField(
            model_name='model',
            name='chain_id',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='model_id',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='pdb_id',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
