# Generated by Django 4.2.5 on 2023-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_remove_model_chain_remove_model_chemokinetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
