# Generated by Django 4.2.5 on 2023-10-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_alter_model_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('pdb_id', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
