# Generated by Django 5.0.1 on 2024-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_pdbdata_model_pdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='sequence',
            field=models.TextField(null=True),
        ),
    ]
