# Generated by Django 5.0.1 on 2024-03-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_model_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='mmcif_text',
            field=models.TextField(null=True),
        ),
    ]
