# Generated by Django 5.0.1 on 2024-03-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_model_mmcif_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='chemokine_similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
