# Generated by Django 4.2.7 on 2023-11-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0014_structure_partner_structure_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amino_acid', models.CharField(max_length=1)),
                ('chain', models.CharField(max_length=1)),
                ('sequence_number', models.SmallIntegerField()),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'residue',
            },
        ),
    ]
