# Generated by Django 4.2.7 on 2024-01-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0011_proteinsegment'),
        ('residue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residue',
            options={'ordering': ['sequence_number']},
        ),
        migrations.RemoveField(
            model_name='residue',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='residue',
            name='structure',
        ),
        migrations.AddField(
            model_name='residue',
            name='amino_acid_three_letter',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.protein'),
        ),
        migrations.AddField(
            model_name='residue',
            name='protein_segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinsegment'),
        ),
        migrations.CreateModel(
            name='ResidueNumberingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20)),
                ('short_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.residuenumberingscheme')),
            ],
            options={
                'db_table': 'residue_generic_numbering_scheme',
            },
        ),
        migrations.CreateModel(
            name='ResidueGenericNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=12)),
                ('protein_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_numbers', to='protein.proteinsegment')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.residuenumberingscheme')),
            ],
            options={
                'db_table': 'residue_generic_number',
                'unique_together': {('scheme', 'label')},
            },
        ),
        migrations.AddField(
            model_name='residue',
            name='generic_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='residue.residuegenericnumber'),
        ),
    ]
