# Generated by Django 5.0.1 on 2024-04-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0003_remove_residue_generic_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='generic_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='residue',
            name='sequence_number',
            field=models.SmallIntegerField(null=True),
        ),
    ]
