# Generated by Django 5.0.6 on 2024-06-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('protein', '0001_initial'),
        ('residue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('chain', models.CharField(max_length=200, null=True)),
                ('organism', models.CharField(max_length=100, null=True)),
                ('unp_accession', models.CharField(blank=True, max_length=50, null=True)),
                ('pfam_accession', models.CharField(blank=True, max_length=50, null=True)),
                ('pubchem_id', models.CharField(blank=True, max_length=255, null=True)),
                ('comp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('chembl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('smiles', models.CharField(blank=True, max_length=500, null=True)),
                ('inchikey', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'structure_entity',
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'structure_entity_type',
            },
        ),
        migrations.CreateModel(
            name='PdbData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb', models.TextField()),
            ],
            options={
                'db_table': 'structure_pdb_data',
            },
        ),
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'structure_type',
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=2, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='structure.entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.entitytype'),
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=50, null=True)),
                ('publication_date', models.DateField(null=True)),
                ('pdb_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink')),
                ('pdb_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
                ('protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='protein.protein')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.publication')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinstate')),
                ('structure_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structuretype')),
            ],
            options={
                'db_table': 'structure',
            },
        ),
        migrations.CreateModel(
            name='Rotamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdbseq_number', models.IntegerField(null=True)),
                ('chain', models.CharField(max_length=1, null=True)),
                ('sequence_number', models.SmallIntegerField(null=True)),
                ('generic_number', models.SmallIntegerField(null=True)),
                ('amino_acid', models.CharField(max_length=1, null=True)),
                ('amino_acid_three_letter', models.CharField(max_length=3, null=True)),
                ('residue_type', models.CharField(choices=[('canonical', 'Canonical'), ('mutated', 'Mutated')], max_length=10, null=True)),
                ('segment', models.CharField(max_length=20, null=True)),
                ('pdbdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
                ('residue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.residue')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'structure_rotamer',
            },
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.residue')),
                ('pdbdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'structure_fragment',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
    ]
