# Generated by Django 4.2.5 on 2023-10-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0007_rename_uniprot_protein_uniprot_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_code', models.CharField(max_length=4, null=True, unique=True)),
                ('method', models.CharField(max_length=50, null=True)),
                ('resolution', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('publication_date', models.DateField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='protein.protein')),
            ],
            options={
                'db_table': 'structure',
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_ID', models.CharField(max_length=1)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain', to='structure.structure')),
            ],
            options={
                'db_table': 'chain',
                'ordering': ['chain_ID'],
            },
        ),
    ]
