# Generated by Django 5.1.2 on 2024-10-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='residues',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
