# Generated by Django 4.2.5 on 2023-10-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_rename_pdb_code_structure_pdb_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chain',
        ),
    ]
