# Generated by Django 5.1.2 on 2024-10-29 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_entity_residues'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=1)),
                ('rmsd', models.FloatField()),
                ('rotation_matrix', models.JSONField()),
                ('translation_vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
        ),
    ]
