# Generated by Django 5.1.2 on 2025-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_entityinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='chain_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
