# Generated by Django 5.1.2 on 2025-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_structure_chain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='state',
            field=models.CharField(blank=True, choices=[('monomer', 'Monomer'), ('dimer', 'Dimer'), ('tetramer', 'Tetramer'), ('polymer', 'Polymer'), (None, 'None')], max_length=20, null=True),
        ),
    ]
