# Generated by Django 4.2.5 on 2023-10-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_remove_structure_protein_structure_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='protein',
        ),
        migrations.AddField(
            model_name='structure',
            name='protein',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
