# Generated by Django 5.1.2 on 2025-02-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_alter_structure_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemokineBindingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemokine_chain', models.CharField(help_text='Chain identifier for the chemokine within the structure.', max_length=10)),
                ('partner_chain', models.CharField(help_text='Chain identifier for the binding partner within the structure.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemokine_entity', models.ForeignKey(help_text='The chemokine entity.', on_delete=django.db.models.deletion.CASCADE, related_name='chemokine_bindings', to='structure.entity')),
                ('partner_entity', models.ForeignKey(help_text='The binding partner entity.', on_delete=django.db.models.deletion.CASCADE, related_name='binding_partner_entities', to='structure.entity')),
                ('structure', models.ForeignKey(help_text='The structure in which the binding pair is observed.', on_delete=django.db.models.deletion.CASCADE, related_name='chemokine_binding_partners', to='structure.structure')),
            ],
            options={
                'verbose_name': 'Chemokine Binding Partner Pair',
                'verbose_name_plural': 'Chemokine Binding Partner Pairs',
                'unique_together': {('structure', 'chemokine_entity', 'partner_entity', 'chemokine_chain', 'partner_chain')},
            },
        ),
    ]
