# Generated by Django 5.1.2 on 2025-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_chemokinebindingpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinebindingpartner',
            name='partner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
