# Generated by Django 5.1.2 on 2025-04-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_chemokinebindingpartner_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemokinebindingpartner',
            name='chemokine_chain',
            field=models.CharField(help_text='Chain identifier for the chemokine within the structure.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chemokinebindingpartner',
            name='chemokine_entity',
            field=models.ForeignKey(help_text='The chemokine entity.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemokine_bindings', to='structure.entity'),
        ),
        migrations.AlterField(
            model_name='chemokinebindingpartner',
            name='partner_chain',
            field=models.CharField(help_text='Chain identifier for the binding partner within the structure.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chemokinebindingpartner',
            name='partner_entity',
            field=models.ForeignKey(help_text='The binding partner entity.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='binding_partner_entities', to='structure.entity'),
        ),
        migrations.AlterField(
            model_name='chemokinebindingpartner',
            name='structure',
            field=models.ForeignKey(help_text='The structure in which the binding pair is observed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemokine_binding_partners', to='structure.structure'),
        ),
    ]
