# Generated by Django 4.2.5 on 2023-10-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0010_protein_pdb_list'),
        ('structure', '0007_remove_structure_protein_structure_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb', models.TextField()),
            ],
            options={
                'db_table': 'pdbdata',
            },
        ),
        migrations.AlterField(
            model_name='structure',
            name='protein',
            field=models.ManyToManyField(related_name='structures', to='protein.protein'),
        ),
        migrations.CreateModel(
            name='Structure_PDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdbdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
            ],
            options={
                'db_table': 'structure_domain',
            },
        ),
    ]
