# Generated by Django 4.2.5 on 2023-10-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_pdbdata_alter_structure_protein_structure_pdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure_pdb',
            name='name',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
