# Generated by Django 5.1.2 on 2025-04-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_alter_chemokinebindingpartner_chemokine_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinebindingpartner',
            name='partner_residues',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
