# Generated by Django 5.1.2 on 2025-04-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_chemokinebindingpartner_partner_residues'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinebindingpartner',
            name='chemokine_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
