# Generated by Django 4.2.7 on 2023-11-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_structure_pdb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='molecule_names',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='structure.structure', to_field='pdb_id')),
            ],
        ),
    ]
