# Generated by Django 5.1.2 on 2025-04-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_chemokinebindingpartner_chemokine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemokinebindingpartner',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chemokinebindingpartner',
            name='pdb_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata'),
        ),
    ]
