# Generated by Django 4.2.7 on 2023-11-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_structure_molecule_names_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'unique_together': {('structure', 'chain_id')},
            },
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
