# Generated by Django 5.1.2 on 2025-04-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_remove_chemokinebindingpartner_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityinstance',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Chain',
        ),
    ]
