# Generated by Django 4.2.7 on 2023-11-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0010_protein_pdb_list'),
        ('structure', '0012_compound_preferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='protein',
        ),
        migrations.AddField(
            model_name='structure',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='protein.protein'),
        ),
    ]
