# Generated by Django 5.1.2 on 2025-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_remove_entityinstance_created_at_delete_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinebindingpartner',
            name='partner_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
