# Generated by Django 4.2.7 on 2023-11-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('protein', '0010_protein_pdb_list'),
        ('structure', '0013_remove_structure_protein_structure_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='partner',
            field=models.ManyToManyField(null=True, to='partner.partner'),
        ),
        migrations.AddField(
            model_name='structure',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='protein.protein'),
        ),
    ]
