# Generated by Django 5.1.2 on 2025-04-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_chemokinebindingpartner_partner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdbdata',
            name='pdb',
            field=models.TextField(max_length=1000000000),
        ),
    ]
