# Generated by Django 5.1.2 on 2025-04-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0014_alter_pdbdata_pdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='chain_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='state',
            field=models.CharField(blank=True, choices=[('monomer', 'Monomer'), ('dimer', 'Dimer'), ('tetramer', 'Tetramer'), ('polymer', 'Polymer'), (None, 'None')], max_length=50, null=True),
        ),
    ]
