# Generated by Django 5.1.2 on 2025-06-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_alter_structure_chain_id_alter_structure_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotamer',
            name='ccn_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
