# Generated by Django 5.1.2 on 2025-06-25 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_alter_partner_options_partner_structures_and_more'),
        ('structure', '0016_rotamer_ccn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemokinebindingpartner',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Link to the partner object if defined in the Partner table.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binding_instances', to='partner.partner'),
        ),
    ]
