# Generated by Django 5.1.2 on 2025-09-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0009_alter_protein_web_links'),
        ('structure', '0017_chemokinebindingpartner_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_text', models.TextField()),
            ],
            options={
                'db_table': 'stats_text',
            },
        ),
        migrations.CreateModel(
            name='PredictedStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('monomer', 'Monomer'), ('dimer', 'Dimer'), ('tetramer', 'Tetramer'), ('polymer', 'Polymer'), (None, 'None')], max_length=50, null=True)),
                ('date_generated', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, help_text='Method used for modeling', max_length=100, null=True)),
                ('pdb_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alphafold_models', to='protein.protein')),
                ('stats_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.statstext')),
            ],
            options={
                'db_table': 'structure_model',
            },
        ),
        migrations.CreateModel(
            name='PredictedComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('monomer', 'Monomer'), ('dimer', 'Dimer'), ('tetramer', 'Tetramer'), ('polymer', 'Polymer'), (None, 'None')], max_length=50, null=True)),
                ('date_generated', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, help_text='Method used for modeling', max_length=100, null=True)),
                ('chemokine_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemokine_complex_models', to='protein.protein')),
                ('gpcr_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpcr_complex_models', to='protein.protein')),
                ('pdb_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
                ('stats_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.statstext')),
            ],
            options={
                'db_table': 'structure_complex_model',
            },
        ),
    ]
