# Generated by Django 5.0.1 on 2024-03-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0021_rename_struct_ref_id_entity_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='segment_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
