# Generated by Django 5.0.1 on 2024-03-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0022_entity_segment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='res_end',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='res_start',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
