# Generated by Django 5.0.1 on 2024-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0024_chain_accession_chain_res_beg_chain_res_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='res_end',
            new_name='pdbx_accession',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='res_start',
            new_name='pfam_accession',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='accession',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='segment_id',
        ),
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
