# Generated by Django 5.0.1 on 2024-03-21 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0025_rename_res_end_entity_pdbx_accession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chain',
            options={},
        ),
        migrations.RenameField(
            model_name='chain',
            old_name='accession',
            new_name='chain',
        ),
        migrations.RenameField(
            model_name='chain',
            old_name='res_beg',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='chain',
            old_name='res_end',
            new_name='pdbx_accession',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='chain_ID',
        ),
        migrations.AddField(
            model_name='chain',
            name='pfam_accession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
        migrations.AlterModelTable(
            name='chain',
            table='structure_chain',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
