# Generated by Django 5.0.1 on 2024-03-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0027_chain_chemokine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chain',
            old_name='chemokine',
            new_name='is_chemokine',
        ),
    ]
