# Generated by Django 5.0.1 on 2024-03-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0035_alter_residue_generic_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residue',
            name='amino_acid_three_letter',
        ),
        migrations.RemoveField(
            model_name='residue',
            name='generic_number',
        ),
        migrations.RemoveField(
            model_name='residue',
            name='sequence_number',
        ),
        migrations.RemoveField(
            model_name='residue',
            name='structure',
        ),
        migrations.AddField(
            model_name='residue',
            name='residue_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='residue',
            name='amino_acid',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
