# Generated by Django 5.0.1 on 2024-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0036_remove_residue_amino_acid_three_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='generic_number',
            field=models.IntegerField(null=True),
        ),
    ]
