# Generated by Django 5.0.1 on 2024-04-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0040_fragment_rotamer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Residue',
        ),
    ]
