# Generated by Django 5.0.1 on 2024-05-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0044_remove_structure_date_remove_structure_doi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'structure_entity_type',
            },
        ),
        migrations.RemoveField(
            model_name='chain',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='contacts_chemokine',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='is_chemokine',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='pdbx_accession',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='pfam_accession',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='type',
        ),
        migrations.AddField(
            model_name='chain',
            name='chain_id',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='chain',
            table=None,
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('chain', models.CharField(max_length=5, null=True)),
                ('organism', models.CharField(max_length=100, null=True)),
                ('unp_accession', models.CharField(max_length=50, null=True)),
                ('pfam_accession', models.CharField(max_length=50, null=True)),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
                ('entity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.entitytype')),
            ],
            options={
                'db_table': 'structure_entity',
            },
        ),
        migrations.AddField(
            model_name='chain',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='structure.entity'),
        ),
    ]
