# Generated by Django 5.0.1 on 2024-05-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0045_entitytype_remove_chain_chain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotamer',
            old_name='residue',
            new_name='canonical_residue',
        ),
        migrations.AddField(
            model_name='rotamer',
            name='amino_acid',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rotamer',
            name='amino_acid_three_letter',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='rotamer',
            name='generic_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rotamer',
            name='residue_type',
            field=models.CharField(choices=[('canonical', 'Canonical'), ('mutated', 'Mutated')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rotamer',
            name='segment',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rotamer',
            name='sequence_number',
            field=models.SmallIntegerField(null=True),
        ),
    ]
