# Generated by Django 5.0.1 on 2024-05-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0047_alter_rotamer_canonical_residue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotamer',
            name='missing_atoms',
        ),
    ]
