# Generated by Django 5.0.1 on 2024-05-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0048_remove_rotamer_missing_atoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotamer',
            old_name='canonical_residue',
            new_name='residue',
        ),
    ]
