# Generated by Django 5.0.6 on 2024-06-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.SmallIntegerField(null=True)),
                ('generic_number', models.SmallIntegerField(null=True)),
                ('amino_acid', models.CharField(max_length=1)),
                ('amino_acid_three_letter', models.CharField(max_length=3, null=True)),
                ('protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
            options={
                'db_table': 'residue',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='ResidueNumberingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20)),
                ('short_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.residuenumberingscheme')),
            ],
            options={
                'db_table': 'residue_generic_numbering_scheme',
            },
        ),
        migrations.CreateModel(
            name='ResidueGenericNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=12)),
                ('protein_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_numbers', to='protein.proteinsegment')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.residuenumberingscheme')),
            ],
            options={
                'db_table': 'residue_generic_number',
                'unique_together': {('scheme', 'label')},
            },
        ),
    ]
