# Generated by Django 5.1.2 on 2025-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='ccn_number',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
