# Generated by Django 5.0.1 on 2024-04-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_alter_residue_options_remove_residue_chain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residue',
            name='generic_number',
        ),
        migrations.RemoveField(
            model_name='residue',
            name='protein_segment',
        ),
    ]
