# Generated by Django 5.1.2 on 2025-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_residue_ccn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residue',
            name='ccn_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
