# Generated by Django 5.1.2 on 2025-06-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0003_alter_residue_ccn_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residue',
            name='generic_number',
        ),
    ]
