# Generated by Django 4.2.5 on 2023-10-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='pdb_code',
            new_name='pdb_id',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='structure',
            name='chains',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='doi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='resolution',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
