# Generated by Django 4.2.5 on 2023-10-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0010_protein_pdb_list'),
        ('structure', '0003_delete_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='protein.protein'),
        ),
    ]
