# Generated by Django 4.2.5 on 2023-10-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0010_protein_pdb_list'),
        ('structure', '0006_remove_structure_protein_structure_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='protein',
        ),
        migrations.AddField(
            model_name='structure',
            name='protein',
            field=models.ManyToManyField(null=True, related_name='structures', to='protein.protein'),
        ),
    ]
