# Generated by Django 4.2.7 on 2023-11-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_compound_delete_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
