# Generated by Django 4.2.7 on 2023-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_remove_partner_chain_remove_partner_pdb_id_and_more'),
        ('structure', '0014_structure_partner_structure_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='partner',
            field=models.ManyToManyField(to='partner.partner'),
        ),
    ]
