# Generated by Django 4.2.7 on 2024-01-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_alter_structure_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'structure_type',
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_ID', models.CharField(max_length=1)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain', to='structure.structure')),
            ],
            options={
                'db_table': 'chain',
                'ordering': ['chain_ID'],
            },
        ),
    ]
