# Generated by Django 4.2.7 on 2024-01-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_structuretype_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='structure_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structuretype'),
        ),
    ]
