# Generated by Django 5.0.1 on 2024-03-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0018_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='molecule_names',
        ),
        migrations.DeleteModel(
            name='Compound',
        ),
    ]
