# Generated by Django 5.0.1 on 2024-03-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0019_remove_structure_molecule_names_delete_compound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='entity_id',
            new_name='struct_ref_id',
        ),
    ]
