# Generated by Django 5.0.1 on 2024-03-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0020_rename_entity_id_entity_struct_ref_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='struct_ref_id',
            new_name='entity_id',
        ),
    ]
