# Generated by Django 5.0.1 on 2024-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0023_entity_res_end_entity_res_start_alter_structure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='accession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='res_beg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='res_end',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
