# Generated by Django 5.0.1 on 2024-03-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0026_alter_chain_options_rename_accession_chain_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='chemokine',
            field=models.BooleanField(null=True),
        ),
    ]
