# Generated by Django 5.0.1 on 2024-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0028_rename_chemokine_chain_is_chemokine'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='contacts_chemokine',
            field=models.BooleanField(null=True),
        ),
    ]
