# Generated by Django 5.0.1 on 2024-03-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0029_chain_contacts_chemokine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='chains',
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=1000, null=True)),
                ('aligned_sequence', models.CharField(max_length=1000, null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.chain')),
            ],
            options={
                'db_table': 'structure_seq',
            },
        ),
    ]
