# Generated by Django 5.0.1 on 2024-03-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0030_remove_structure_chains_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
                ('number', models.CharField(max_length=1000, null=True)),
                ('gen_number', models.CharField(max_length=1000, null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.chain')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'structure_residue',
            },
        ),
    ]
