# Generated by Django 5.0.1 on 2024-03-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0031_residue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemokineInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_pdb_path', models.CharField(blank=True, help_text='Path to the generated PDB file', max_length=255, null=True)),
                ('chemokine_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemokine_focus', to='structure.chain')),
                ('contacting_chains', models.ManyToManyField(related_name='contacting_chemokine', to='structure.chain')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemokine_interactions', to='structure.structure')),
            ],
            options={
                'db_table': 'structure_chemokine_interaction',
            },
        ),
    ]
