# Generated by Django 5.0.1 on 2024-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0032_chemokineinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residue',
            name='gen_number',
        ),
        migrations.RemoveField(
            model_name='residue',
            name='number',
        ),
        migrations.RemoveField(
            model_name='residue',
            name='type',
        ),
        migrations.AddField(
            model_name='residue',
            name='amino_acid',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='amino_acid_three_letter',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='generic_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='sequence_number',
            field=models.IntegerField(null=True),
        ),
    ]
