# Generated by Django 5.0.1 on 2024-03-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0033_remove_residue_gen_number_remove_residue_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residue',
            name='generic_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='residue',
            name='sequence_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
