# Generated by Django 5.0.1 on 2024-03-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0034_alter_residue_generic_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residue',
            name='generic_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='residue',
            name='sequence_number',
            field=models.IntegerField(null=True),
        ),
    ]
