# Generated by Django 5.0.1 on 2024-04-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('protein', '0017_gene'),
        ('structure', '0037_residue_generic_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='pdb_id',
            new_name='pdb_code',
        ),
        migrations.AddField(
            model_name='structure',
            name='pdb_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata'),
        ),
        migrations.AddField(
            model_name='structure',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.publication'),
        ),
        migrations.AddField(
            model_name='structure',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinstate'),
        ),
    ]
