# Generated by Django 5.0.1 on 2024-04-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('structure', '0038_rename_pdb_id_structure_pdb_code_structure_pdb_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='pdb',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='pdb_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink'),
        ),
    ]
