# Generated by Django 5.0.1 on 2024-04-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0002_alter_residue_options_remove_residue_chain_and_more'),
        ('structure', '0039_structure_pdb_alter_structure_pdb_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdbdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.residue')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'structure_fragment',
            },
        ),
        migrations.CreateModel(
            name='Rotamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_atoms', models.BooleanField(default=False)),
                ('pdbdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.residue')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'structure_rotamer',
            },
        ),
    ]
