# Generated by Django 5.0.1 on 2024-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0041_delete_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotamer',
            name='pdbseq_number',
            field=models.IntegerField(null=True),
        ),
    ]
