# Generated by Django 5.0.1 on 2024-04-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0042_rotamer_pdbseq_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='structure_pdb',
            name='pdbdata',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='pdb',
        ),
        migrations.AlterModelTable(
            name='pdbdata',
            table='structure_pdb_data',
        ),
        migrations.DeleteModel(
            name='ChemokineInteraction',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.DeleteModel(
            name='Structure_PDB',
        ),
    ]
