# Generated by Django 5.0.1 on 2024-04-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0043_remove_sequence_chain_remove_structure_pdb_pdbdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='date',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='method',
        ),
    ]
