# Generated by Django 5.0.1 on 2024-05-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0004_residue_generic_number_alter_residue_sequence_number'),
        ('structure', '0046_rename_residue_rotamer_canonical_residue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotamer',
            name='canonical_residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.residue'),
        ),
    ]
