# Generated by Django 5.0.1 on 2024-05-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0049_rename_canonical_residue_rotamer_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotamer',
            name='chain',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
