# Generated by Django 4.2.5 on 2023-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chain', models.CharField(max_length=1)),
                ('uniprot_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('family', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('sequence', models.CharField(max_length=200)),
                ('chemokinetype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PDBInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=4)),
                ('method', models.CharField(max_length=50)),
                ('organism_name', models.CharField(max_length=50)),
                ('chain_ids', models.CharField(max_length=50)),
                ('doi', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
