# Generated by Django 4.2.5 on 2023-10-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_pdbinfo_resolution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDBInfo',
        ),
    ]
