# Generated by Django 4.2.5 on 2023-10-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_alter_model_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='model',
            table='model',
        ),
    ]
