# Generated by Django 4.2.7 on 2023-11-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb', models.TextField()),
            ],
            options={
                'db_table': 'Model_pdbdata',
            },
        ),
        migrations.CreateModel(
            name='Model_PDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, null=True, unique=True)),
                ('pdbdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.pdbdata')),
            ],
            options={
                'db_table': 'Model_PDB',
            },
        ),
    ]
