# Generated by Django 5.0.1 on 2024-03-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_model_chemokine_similarity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='chemokine_similarity_score',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
