# Generated by Django 5.0.1 on 2024-03-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_alter_model_chemokine_similarity_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='chain_id',
        ),
        migrations.AddField(
            model_name='model',
            name='db_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='db_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='entity_ref_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_id',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
