# Generated by Django 5.0.6 on 2024-06-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinSequenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'protein_sequence_type',
            },
        ),
        migrations.CreateModel(
            name='ProteinSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'protein_source',
            },
        ),
        migrations.CreateModel(
            name='ProteinState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'protein_state',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uniprot_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('family', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('sequence', models.CharField(max_length=1000, null=True)),
                ('accession', models.CharField(db_index=True, max_length=100, null=True)),
                ('web_links', models.ManyToManyField(to='common.weblink')),
                ('sequence_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinsequencetype')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinsource')),
            ],
            options={
                'db_table': 'protein',
            },
        ),
        migrations.CreateModel(
            name='ProteinAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.SmallIntegerField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
            options={
                'db_table': 'protein_alias',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ProteinFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinfamily')),
            ],
            options={
                'db_table': 'protein_family',
            },
        ),
        migrations.CreateModel(
            name='ProteinSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('proteinfamily', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'protein_segment',
                'ordering': ('id',),
                'unique_together': {('slug', 'proteinfamily')},
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=200)),
                ('affinity', models.CharField(max_length=50)),
                ('affinity_parameter', models.CharField(max_length=50, null=True)),
                ('species', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=100, null=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='protein.protein')),
            ],
            options={
                'db_table': 'protein_target',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.SmallIntegerField()),
                ('proteins', models.ManyToManyField(related_name='genes', to='protein.protein')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.species')),
            ],
            options={
                'db_table': 'gene',
                'ordering': ('position',),
                'unique_together': {('name', 'species', 'position')},
            },
        ),
    ]
