# Generated by Django 5.0.6 on 2024-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='accession',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='family',
        ),
        migrations.AddField(
            model_name='protein',
            name='full_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='gene_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='iuphar',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='subfamily',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
