# Generated by Django 5.1.2 on 2024-10-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_remove_protein_accession_remove_protein_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPCRProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gpcr_class', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('endogenous_ligand', models.CharField(blank=True, max_length=200, null=True)),
                ('g_protein_coupling', models.CharField(blank=True, max_length=100, null=True)),
                ('signaling_pathways', models.JSONField(blank=True, null=True)),
                ('residues', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gpcr_protein',
            },
        ),
    ]
