# Generated by Django 4.2.5 on 2023-10-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_uniprot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=100, unique=True)),
                ('common_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.AlterModelTable(
            name='protein',
            table=None,
        ),
    ]
