# Generated by Django 4.2.5 on 2023-10-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_species_alter_protein_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinfamily')),
            ],
            options={
                'db_table': 'protein_family',
            },
        ),
    ]
