# Generated by Django 5.1.2 on 2024-10-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_gpcrprotein'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpcrprotein',
            name='unp_accession',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
