# Generated by Django 5.1.2 on 2025-02-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0004_gpcrprotein_unp_accession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('sequence', models.TextField()),
                ('protein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal_sequence', to='protein.protein')),
            ],
            options={
                'verbose_name': 'Signal Sequence',
                'verbose_name_plural': 'Signal Sequences',
                'ordering': ['protein'],
            },
        ),
    ]
