# Generated by Django 4.2.5 on 2023-10-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0004_proteinfamily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='latin_name',
            field=models.CharField(max_length=200),
        ),
    ]
