# Generated by Django 5.1.2 on 2025-02-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0005_signalsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalsequence',
            name='generic_end',
            field=models.CharField(blank=True, help_text="Generic numbering for the signal sequence end (e.g., 'SS21')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signalsequence',
            name='generic_start',
            field=models.CharField(blank=True, help_text="Generic numbering for the signal sequence start (e.g., 'SS1')", max_length=20, null=True),
        ),
    ]
