# Generated by Django 5.1.2 on 2025-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('protein', '0006_signalsequence_generic_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='web_links',
            field=models.ManyToManyField(null=True, to='common.weblink'),
        ),
    ]
