# Generated by Django 4.2.5 on 2023-10-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0006_rename_uniprot_uniprot_uniprot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protein',
            old_name='uniprot',
            new_name='uniprot_id',
        ),
        migrations.AlterModelTable(
            name='protein',
            table='protein',
        ),
    ]
