# Generated by Django 4.2.5 on 2023-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0007_rename_uniprot_protein_uniprot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='sequence',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
