# Generated by Django 5.1.2 on 2025-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('protein', '0008_delete_proteinstate_alter_gene_table_delete_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='web_links',
            field=models.ManyToManyField(to='common.weblink'),
        ),
    ]
