# Generated by Django 4.2.5 on 2023-10-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0009_delete_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='pdb_list',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
