# Generated by Django 4.2.7 on 2024-01-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0010_protein_pdb_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('fully_aligned', models.BooleanField(default=False)),
                ('partial', models.BooleanField(default=False)),
                ('proteinfamily', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'protein_segment',
                'ordering': ('id',),
                'unique_together': {('slug', 'proteinfamily')},
            },
        ),
    ]
