# Generated by Django 4.2.7 on 2024-01-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0011_proteinsegment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteinsegment',
            name='fully_aligned',
        ),
        migrations.RemoveField(
            model_name='proteinsegment',
            name='partial',
        ),
        migrations.AddField(
            model_name='proteinsegment',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proteinsegment',
            name='start',
            field=models.IntegerField(null=True),
        ),
    ]
