# Generated by Django 5.0.1 on 2024-04-15 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0013_proteinsequencetype_proteinstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'protein_source',
            },
        ),
        migrations.AddField(
            model_name='protein',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinsource'),
        ),
    ]
