# Generated by Django 5.0.1 on 2024-04-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0015_protein_web_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.SmallIntegerField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
            options={
                'db_table': 'protein_alias',
                'ordering': ('position',),
            },
        ),
    ]
