# Generated by Django 5.0.6 on 2024-06-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partner',
            },
        ),
        migrations.CreateModel(
            name='PDBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb', models.TextField()),
            ],
            options={
                'db_table': 'partner_pdbdata',
            },
        ),
        migrations.CreateModel(
            name='PartnerEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unp_accession', models.CharField(blank=True, max_length=50, null=True)),
                ('pfam_accession', models.CharField(blank=True, max_length=50, null=True)),
                ('comp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('chembl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='structure.entity')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='partner.partner')),
            ],
            options={
                'db_table': 'partner_entity',
            },
        ),
        migrations.CreateModel(
            name='Partner_PDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, null=True, unique=True)),
                ('pdbdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.pdbdata')),
            ],
            options={
                'db_table': 'partner_pdb',
            },
        ),
    ]
