# Generated by Django 5.0.6 on 2024-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
