# Generated by Django 5.1.2 on 2025-04-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partner_type'),
        ('structure', '0013_chemokinebindingpartner_partner_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AddField(
            model_name='partner',
            name='structures',
            field=models.ManyToManyField(blank=True, related_name='partners', to='structure.structure'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
