# Generated by Django 4.2.7 on 2023-11-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partner_pdb_id_alter_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='chain',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
