# Generated by Django 4.2.7 on 2023-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partner_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='chain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
