# Generated by Django 4.2.7 on 2023-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0014_structure_partner_structure_state_and_more'),
        ('partner', '0005_pdbdata_partner_pdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='pdb_id',
        ),
        migrations.AddField(
            model_name='partner',
            name='pdbs',
            field=models.ManyToManyField(related_name='partners', to='structure.structure'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
