# Generated by Django 4.2.7 on 2023-11-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_remove_partner_chain_remove_partner_pdb_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='pdbs',
            new_name='structures',
        ),
    ]
