# Generated by Django 5.0.1 on 2024-04-15 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_rename_pdbs_partner_structures'),
        ('structure', '0037_residue_generic_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ligand_type',
            },
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='type',
            new_name='partner_type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='structures',
        ),
        migrations.AddField(
            model_name='partner',
            name='clean_inchikey',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='hacc',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='hdon',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='inchikey',
            field=models.CharField(max_length=27, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='logp',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='mw',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='rotatable_bonds',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='sequence',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='smiles',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PartnerProteinStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=20)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure')),
            ],
            options={
                'db_table': 'partner_protein_structure',
            },
        ),
    ]
